sudo: false
language: java
addons:
  apt_packages:
   - python-pip
   - python-virtualenv
   - python-dev
   - libffi-dev
   - python-swiftclient
jdk:
  - oraclejdk8
script:
 - mvn test
 - ./src/test/resources/run-swift-tests.sh
 - ./src/test/resources/run-swiftclient-python-tests.sh
