sudo: false
language: java
addons:
  apt_packages:
   - python-pip
   - python-virtualenv
   - python-dev
   - liberasurecode-dev
   - libffi-dev
jdk:
  - oraclejdk8
# TODO: work around travis-ci/travis-ci#4629
before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
script:
 - mvn test
 - ./src/test/resources/run-tests.sh
