language: java
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-pip python-virtualenv python-dev libffi-dev
jdk:
  - oraclejdk8
after_script: src/test/resources/run-swift-tests.sh
